# Generated by Django 5.2.4 on 2025-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('intro', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('links', models.TextField(blank=True, help_text='Comma-separated or JSON list of links')),
                ('image_url', models.URLField(blank=True, help_text='URL of the image to download')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='nutrients/')),
            ],
        ),
    ]
