# Generated by Django 5.2.4 on 2025-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='conditions_of_growth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='health_contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='link_to_wikipedia',
            field=models.URLField(blank=True, help_text='Link to Wikipedia page for this crop.', null=True),
        ),
    ]
