# Generated by Django 5.2.3 on 2025-06-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCrop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confidence', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.recommendation')),
            ],
            options={
                'db_table': 'recommendation_crops',
            },
        ),
    ]
