# Generated by Django 5.2.3 on 2025-06-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_recommendation_is_deleted'),
        ('recommendationcrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationcrop',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_crops', to='recommendation.recommendation'),
        ),
    ]
