# Generated by Django 5.2.3 on 2025-06-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationcrop', '0002_alter_recommendationcrop_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationcrop',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
