# Generated by Django 5.2.3 on 2025-06-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
